# destroy.yml
---
- name: Destroy Australian Proxy
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/all.yml
  tasks:
    - name: Get Linode instance
      community.linode.linode_info:
        api_token: "{{ lookup('env', 'LINODE_TOKEN') }}"
        filters:
          label: "au-proxy"
      register: linode_info

    - name: Delete Linode instance
      community.general.linode:
        api_token: "{{ lookup('env', 'LINODE_TOKEN') }}"
        label: "au-proxy"
        state: absent
      when: linode_info.instances | length > 0

    - name: Remove DNS record
      uri:
        url: "https://api.linode.com/v4/domains/{{ proxy_domain.split('.')[-2:] | join('.') }}/records"
        method: DELETE
        headers:
          Authorization: "Bearer {{ lookup('env', 'LINODE_TOKEN') }}"
        status_code: [200, 204]
      when: linode_info.instances | length > 0
