- name: Firewall
  hosts: tag_proxies
  gather_facts: false
  become: true
  become_user: root
  tasks:

    - name: Configure UFW
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - "{{ ssh_port }}"
        - "{{ proxy_port }}"

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny