- name: Swap File
  hosts: tag_proxies
  gather_facts: false
  become: true
  become_user: root
  tasks:

    - name: Create swap file
      command: dd if=/dev/zero of=/swapfile bs=1M count=1024

    - name: Set swap file permissions
      file:
        path: /swapfile
        mode: '0600'

    - name: Make swap
      command: mkswap /swapfile

    - name: Enable swap
      command: swapon /swapfile

    - name: Add swap to fstab
      lineinfile:
        path: /etc/fstab
        line: '/swapfile none swap sw 0 0'

    - name: Set swappiness
      sysctl:
        name: vm.swappiness
        value: '10'
        state: present