- name: Ssh
  hosts: tag_proxies
  gather_facts: false
  become: true
  become_user: root
  tasks:

    - name: Add sudo group to allowed SSH users
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "AllowGroups sudo"
        insertbefore: "^PermitRootLogin"

    - name: Configure SSH security
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        validate: '/usr/sbin/sshd -t -f %s'
      loop:
        - {regexp: '^#?PermitRootLogin', line: 'PermitRootLogin no'}
        - {regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no'}
        - {regexp: '^#?MaxAuthTries', line: 'MaxAuthTries 3'}
        - {regexp: '^#?LoginGraceTime', line: 'LoginGraceTime 30'}

    - name: Configure fail2ban for SSH
      copy:
        dest: /etc/fail2ban/jail.d/sshd.conf
        content: |
          [sshd]
          enabled = true
          port = {{ ssh_port }}
          filter = sshd
          logpath = /var/log/auth.log
          maxretry = 3
          findtime = 300
          bantime = 3600

    - name: Configure sshd logrotate
      copy:
        dest: /etc/logrotate.d/sshd
        content: |
          /var/log/auth.log {
          weekly
          rotate 4
          compress
          missingok
          notifempty
          }
