---
- name: FIREWALL | Configure UFW
  tags: 'firewall'
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "{{ ssh_port }}"
    - "{{ proxy_port }}"
    - 80
    - 443

- name: FIREWALL | Enable UFW
  tags: 'firewall'
  ufw:
    state: enabled
    policy: deny
