# destroy.yml
---
- name: Destroy Proxy Instances
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Delete instance
      linode.cloud.instance:
        api_token: "{{ lookup('env', 'LINODE_API_TOKEN') }}"
        label: "{{ instance_name }}"
        state: absent
      delegate_to: localhost

    - name: Remove DNS record
      linode.cloud.domain_record:
        api_token: "{{ lookup('env', 'LINODE_API_TOKEN') }}"
        domain: "{{ proxy_domain }}"
        type: "A"
        name: "{{ instance_name }}"
        state: absent
      delegate_to: localhost
